// Regenerates src/icons.js from a local Font Awesome Free package.
//
// Navy ships the icons it uses as inline SVG paths rather than the Font Awesome
// webfont or its CSS: a VS Code webview would otherwise need a font-src CSP
// entry and a ~400KB woff2 for two dozen glyphs, and a font renders as a
// missing-glyph box if it fails to load. The generated file is committed, so a
// build — and the extension at runtime — never needs the network or the
// Font Awesome package at all. This script exists only to change the SET.
//
//   npm pack @fortawesome/fontawesome-free@7.3.1   # then extract it somewhere
//   node tools/build-icons.js --fa <path-to-extracted-package>
//
// Defaults to node_modules/@fortawesome/fontawesome-free when --fa is omitted.
//
// Licence: Font Awesome Free icons are CC BY 4.0, which requires attribution.
// The generated file carries the notice, and so does the README — do not strip
// either one. https://fontawesome.com/license/free

const fs = require('fs');
const path = require('path');

// Navy's semantic name → the Font Awesome Free solid icon behind it. The
// indirection is the point: renaming Navy's `refactor` icon to a different
// glyph is a one-line change here rather than a hunt through the webview, and
// call sites read as what they mean rather than what they look like.
const ICON_MAP = {
  // Slash commands
  fix: 'wrench',
  explain: 'lightbulb',
  review: 'clipboard-check',
  test: 'circle-check',
  'gen-tests': 'flask',
  optimize: 'bolt',
  security: 'lock',
  commit: 'code-commit',
  pr: 'code-pull-request',
  'pr-review': 'eye',
  refactor: 'arrows-rotate',
  docs: 'book',
  debug: 'bug',
  web: 'globe',
  run: 'play',
  background: 'gear',
  // Panel furniture
  close: 'xmark',
  check: 'check',
  settings: 'gear',
  search: 'magnifying-glass',
  edit: 'pen-to-square',
  copy: 'copy',
  plus: 'plus',
  external: 'arrow-up-right-from-square',
  collapsed: 'up-down',
  'expand-more': 'chevron-down',
  'expand-less': 'chevron-up',
  // Status
  warning: 'triangle-exclamation',
  info: 'circle-exclamation',
  running: 'circle',
  stopped: 'stop',
  process: 'microchip',
  tool: 'gears',
  reasoning: 'brain',
  // Composer / messages
  attachment: 'paperclip',
  image: 'image',
  speak: 'volume-high',
  // Conversation rewind. rotate-left is the canonical undo arrow, and reads as
  // "go back" rather than "run again" — which arrows-rotate (Navy's refactor)
  // does, and is why the two are not shared.
  rewind: 'rotate-left',
  'speak-stop': 'circle-stop',
};

function main() {
  const argIdx = process.argv.indexOf('--fa');
  const faRoot = argIdx !== -1
    ? process.argv[argIdx + 1]
    : path.join(__dirname, '..', 'node_modules', '@fortawesome', 'fontawesome-free');
  const solid = path.join(faRoot, 'svgs', 'solid');
  if (!fs.existsSync(solid)) {
    console.error(`No Font Awesome SVGs at ${solid}\n` +
      'Pass --fa <path to an extracted @fortawesome/fontawesome-free package>.');
    process.exit(1);
  }

  const out = {};
  for (const [name, fa] of Object.entries(ICON_MAP)) {
    const file = path.join(solid, fa + '.svg');
    if (!fs.existsSync(file)) { console.error(`missing FA icon: ${fa}.svg`); process.exit(1); }
    const svg = fs.readFileSync(file, 'utf8');
    const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
    // Every FA solid icon is a single <path>. Bail loudly rather than emit half
    // an icon if that ever stops being true for one of them.
    const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
    if (!viewBox || paths.length !== 1) {
      console.error(`unexpected SVG shape for ${fa}.svg (${paths.length} paths)`);
      process.exit(1);
    }
    out[name] = { fa, viewBox, path: paths[0] };
  }

  const faVersion = JSON.parse(
    fs.readFileSync(path.join(faRoot, 'package.json'), 'utf8')).version;

  const body = Object.entries(out)
    .map(([name, i]) =>
      `  '${name}': { fa: '${i.fa}', viewBox: '${i.viewBox}', path: '${i.path}' },`)
    .join('\n');

  const file = `// GENERATED by tools/build-icons.js — do not edit by hand.
// Font Awesome Free ${faVersion} (https://fontawesome.com), icons licensed
// CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). Attribution is a
// condition of that licence: keep this notice and the one in the README.
//
// Only the icons Navy actually draws are here, as raw path data, so the panel
// needs no webfont, no CSS framework and no network — see tools/build-icons.js
// for how to change the set.

const ICONS = {
${body}
};

// One <symbol> per icon, emitted once into the document so every icon after it
// is a ~40-byte <use> rather than a repeated copy of the path. Hidden with
// both an attribute and inline style: display:none on the <svg> is what keeps
// the sprite from taking up a line box at the top of the panel.
function spriteHtml() {
  const symbols = Object.entries(ICONS)
    .map(([name, i]) => \`<symbol id="i-\${name}" viewBox="\${i.viewBox}"><path d="\${i.path}"/></symbol>\`)
    .join('');
  return \`<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true" id="iconSprite">\${symbols}</svg>\`;
}

// An icon as markup. Decorative by default (aria-hidden) because every icon in
// Navy sits next to its own text label or on a button that already carries an
// aria-label — an icon that announced itself as well would say everything
// twice. Pass a label only where the icon is genuinely the only content.
function icon(name, cls = '', label = '') {
  // The name reaches an href attribute, and one call site takes it from a
  // slash-command definition a repository can write — so anything that is not
  // an icon id is dropped rather than trusted. An unknown-but-clean name simply
  // renders nothing, which is the right failure for a decorative glyph.
  const id = String(name).replace(/[^a-z0-9-]/g, '');
  const className = cls ? 'icon ' + cls : 'icon';
  const a11y = label ? \`role="img" aria-label="\${label}"\` : 'aria-hidden="true"';
  return \`<svg class="\${className}" \${a11y}><use href="#i-\${id}"/></svg>\`;
}

module.exports = { ICONS, spriteHtml, icon };
`;

  const dest = path.join(__dirname, '..', 'src', 'icons.js');
  fs.writeFileSync(dest, file);
  console.log(`wrote ${path.relative(path.join(__dirname, '..'), dest)} — ` +
    `${Object.keys(out).length} icons from Font Awesome Free ${faVersion}`);
}

main();
